### ISSUE TITLE
Precisa ter quebra de linha para adequar o texto dentro do elemento

### ISSUE THREAD

**Issue by Lizbiruel** [bireme/clinical-algorithms#10]
![2_precisa ter quebra de linha para adequar o texto escrito](https://github.com/bireme/clinical-algorithms/assets/25793512/3e2481dc-a36c-44f9-afe5-5ab4db1b392d)
Precisa ter quebra de linha para adequar o texto dentro do elemento

**Comment by RobertoPinaRizzo** [comment]
Sim, o texto de cada nó tem hoje limitações de tamanho, fonte, cor e quebra de linhas. O ponto está na lista de pendências e precisamos examinar se dá para melhorar isto sem precisar da versão paga do JointJS.

**Comment by Lizbiruel** [comment]
RESOLVIDO
