### ISSUE TITLE
O inicio Bola (verde-inicio) deveria ser colocado o problema

### ISSUE THREAD

**Issue by Lizbiruel** [bireme/clinical-algorithms#11]
![3_o inicio BOLA_deveria ser onde coloco o problema](https://github.com/bireme/clinical-algorithms/assets/25793512/ddf083ec-3811-47e9-ab9a-6ff7bd48b12f)
Paciente con sospecha de Arbovirosis por síntomas compatibles y situação (ESSE É O PROBLEMA)
a ação vem depois, não entendo para que serve a bola (verde-inicio) se não consigo escrever dentro dela

**Comment by RobertoPinaRizzo** [comment]
A inserção de textos no item de "Início" e "Término", bem como nos conectores, será implementada via estruturas parametrizadas de metadados (está no backlog).

**Comment by Lizbiruel** [comment]
não necessário
