### ISSUE TITLE
Inserir bloco fixo

### ISSUE THREAD

**Issue by Lizbiruel** [bireme/clinical-algorithms#12]
![O que é INSERIR BLOCO FIXO](https://github.com/bireme/clinical-algorithms/assets/25793512/5d7582fe-93e9-4cb0-92b4-7a7c81dec763)
Não entendi o sentido de 'INSERIR BLOCO FIXO'

**Comment by RobertoPinaRizzo** [comment]
Através deste botão de "INSERIR BLOCO FIXO" podemos inserir um novo bloco de recomendação formal, boa prática ou recomendação informal, na área de metadados associada, cada uma, a um nó.

**Comment by Lizbiruel** [comment]
ok, entendido
