### ISSUE TITLE
Não tem SALVE no final do formulário

### ISSUE THREAD

**Issue by Lizbiruel** [bireme/clinical-algorithms#13]
![Não tem SALVE no final desse formulário](https://github.com/bireme/clinical-algorithms/assets/25793512/9b0f0703-1058-46c5-97a4-2e16f67fc8b3)
Não tem SALVE no final do formulário

**Comment by RobertoPinaRizzo** [comment]
O botão "SALVAR" da parte de baixo da tela salva tudo (desenho e metadados).

**Comment by Lizbiruel** [comment]
ok, entendido
