### ISSUE TITLE
Caixa de INICIO

### ISSUE THREAD

**Issue by Lizbiruel** [bireme/clinical-algorithms#15]
![inicio_não consigo colocar informação dentro desse elemento](https://github.com/bireme/clinical-algorithms/assets/25793512/a430dd4a-2642-4174-9088-987c3b03222e)

não consigo colocar informação dentro do circulo INICIO

**Comment by RobertoPinaRizzo** [comment]
Será possível colocar texto no item de Início (e Término também) via metadados parametrizados. Será implementado.

**Comment by Lizbiruel** [comment]
estamos aguardando

**Comment by RobertoPinaRizzo** [comment]
Os metadados parametrizados (que resolveriam a questão) não tiveram priorização suficiente para serem implementados. Em eventual retomada dos trabalhos, o assunto poderá ser retomado.
