### ISSUE TITLE
Recomendaciones/ Buenas Prácticas no enunciado

### ISSUE THREAD

**Issue by Lizbiruel** [bireme/clinical-algorithms#17]
![recomendaciones_ buenas practicas](https://github.com/bireme/clinical-algorithms/assets/25793512/30247e0a-4e9e-48e9-baf8-97c85edeb7a0)
o titulo da caixa - Recomendaciones/ Buenas Prácticas (no enunciado) deveria ser somente Recomendaciones

**Comment by RobertoPinaRizzo** [comment]
Mudança será priorizada e realizada em eventual retomada dos trabalhos.
