### ISSUE TITLE
Não consigo fixar a SETA na caixa lateral

### ISSUE THREAD

**Issue by Lizbiruel** [bireme/clinical-algorithms#19]
![Uploading não consigo fixar a seta na lateral.png…]()

**Comment by Lizbiruel** [comment]
![não consigo fixar a seta na lateral](https://github.com/bireme/clinical-algorithms/assets/25793512/bcd5ef83-686b-4f7f-94fc-3fce4373f4b0)

**Comment by RobertoPinaRizzo** [comment]
As setas só podem parte das bases dos nós na versão atual. Está registrada a melhoria de a seta poder partir de qualquer face, para priorização na eventual retomada dos trabalhos.
