### ISSUE TITLE
Tipo de intervencion

### ISSUE THREAD

**Issue by Lizbiruel** [bireme/clinical-algorithms#22]
Acredito que tenha outras questões que deveriam ser colocada como opção: Tratamento, Prevenção, Diagnóstico, Etiologia, Prognóstico

Vamos confirmar com os clientes.
![terapia_prevenção_ diagnóstico_ etiologia _ prognóstico](https://github.com/bireme/clinical-algorithms/assets/25793512/9b8aed98-ea12-4055-8962-99ba9d0372be)

**Comment by RobertoPinaRizzo** [comment]
Necessária definição e priorização para tratamento em eventual retomada dos trabalhos.
