### ISSUE TITLE
setas flexíveis seriam mais indicadas

### ISSUE THREAD

**Issue by Lizbiruel** [bireme/clinical-algorithms#24]
![setas flexiveis seriam mais indicadas](https://github.com/bireme/clinical-algorithms/assets/25793512/e25cb13a-ca11-4f17-aba1-bf32a90f47eb)

**Comment by RobertoPinaRizzo** [comment]
Este algoritmo é bem antigo. Depois dele já foram implementadas setas flexíveis.
