### ISSUE TITLE
Plataforma do Algoritmo Clinico não esta abrindo - link https://clinical-algorithms.test.bireme.org/algorithms

### ISSUE THREAD

**Issue by Lizbiruel** [bireme/clinical-algorithms#39]
![Captura de tela 2024-01-18 082450](https://github.com/bireme/clinical-algorithms/assets/25793512/075bbd41-0994-468c-a1df-682d2572744e)

**Comment by heitorbarbieri** [comment]
@gabriel-silveira  

 Embora os links abaixo estejam funcionando, 

    https://clinical-algorithms.test.bireme.org/admin/ (edição)
    https://clinical-algorithms.test.bireme.org/ (pesquisa)

 O link https://clinical-algorithms.test.bireme.org/algorithms não está. 
 Você tem alguma ideia do porquê? 

Obrigado

**Comment by heitorbarbieri** [comment]
@gabriel-silveira, você tem alguma previsão caso seja algum problema no desenvolvimento ou dica de possível solução, caso o problema seja interno BIREME? Obrigado.

**Comment by heitorbarbieri** [comment]
Se ajudar, uma chamada à url: https://clinical-algorithms.test.bireme.org/algorithms  retorna código 200 e tem como conteúdo:

```<!DOCTYPE html>
<html>
   <head>
      <base href=/ >
      <title>PAHO Frontend</title>
      <meta charset=utf-8>
      <meta name=description content="PAHO flowchart editor.">
      <meta name=format-detection content="telephone=no">
      <meta name=msapplication-tap-highlight content=no>
      <meta name=viewport content="user-scalable=no,initial-scale=1,maximum-scale=1,minimum-scale=1,width=device-width">
      <link rel=icon href=/imgs/favicon.ico type=image/vnd.microsoft.icon>
      <link rel=stylesheet type=text/css href=/css/joint.css>
      <script defer src=vendor.js></script><script defer src=app.js></script>
   </head>
   <body>
      <div id=q-app></div>
   </body>
</html>

**Comment by gabriel-silveira** [comment]
Esta URL https://clinical-algorithms.test.bireme.org/algorithms não existe.
Porque vocês estão tentando acessar ela?
É a mesma coisa que acessar https://clinical-algorithms.test.bireme.org/xyz, por exemplo.

**Comment by gabriel-silveira** [comment]
Para acessar a lista de algoritmos e editar, por favor entrem na seguinte URL:
https://clinical-algorithms.test.bireme.org/admin
