### ISSUE TITLE
Instrução Inicial para novos usuários

### ISSUE THREAD

**Issue by Lizbiruel** [bireme/clinical-algorithms#45]
O que são as CATEGORIAS, 1,2,3, no registro de um novo algoritmo?

**Comment by RobertoPinaRizzo** [comment]
As categorias são espécies de grupos de algoritmos. Por exemplo: algoritmos de doenças endêmicas, algoritmos de manejo de feridos em campos de batalha, algoritmos oncológicos etc. São categorizações opcionais.

**Comment by Lizbiruel** [comment]
não entendi. As categorias são só um exemplo, eu estava falando do vídeo de instrução de uso da aplicação
