### ISSUE TITLE
Flexibilidade nos TRAÇOS entre as caixa de elementos

### ISSUE THREAD

**Issue by Lizbiruel** [bireme/clinical-algorithms#46]
As linhas que ligam um elemento ao outro, para formar o fluxograma, deveria ser flexível, e deveria partir das quatro fases da figura (quadro) e não apenas na base inferior do quadrado, como esta no momento. E poderiam ser linhas retas ou não sem ser necessariamente uma seta

**Comment by RobertoPinaRizzo** [comment]
As linhas já são flexíveis. Falta de fato poderem partir de todas as faces dos nós e não somente da base. Melhoria a ser priorizada em eventual retomada dos trabalhos.
