### ISSUE TITLE
Diabetes veja o exemplo

### ISSUE THREAD

**Issue by Lizbiruel** [bireme/clinical-algorithms#49]
<img width="652" alt="exemplo diabetes" src="https://github.com/bireme/clinical-algorithms/assets/25793512/b49b3395-9829-45c7-a711-0f678f14acb7">
Eu não consigo fazer um fluxograma, nesta necessidade, faltam elementos essenciais que ajudariam no entendimento, exemplo: ajustar cores das figuras geométricas, dimensionamento das figuras geométricas, linhas transversais, possibilidade de indicar SIM ou NÃO acima das linhas, linhas que parte das linhas e não das BASES das figuras geométricas.

**Comment by Lizbiruel** [comment]
https://diretriz.diabetes.org.br/classificacao-do-diabetes/

**Comment by RobertoPinaRizzo** [comment]
Melhoria a ser avaliada em eventual retomada do projeto.
