### ISSUE TITLE
Abertura da ficha de anotação

### ISSUE THREAD

**Issue by Lizbiruel** [bireme/clinical-algorithms#50]
Abertura da ficha de anotação, atrapalha quando vc quer colocar a figura geométrica e digitar dentro da figura, a ficha é grande e abre em cima da figura geométrica
<img width="629" alt="folha de anotação atrapalha" src="https://github.com/bireme/clinical-algorithms/assets/25793512/656f265c-ab9d-4284-aada-c5065172115e">

**Comment by RobertoPinaRizzo** [comment]
Melhoria a ser avaliada em eventual retomada do projeto.
