### ISSUE TITLE
PDF - falta nome das subdivisões

### ISSUE THREAD

**Issue by SJanostiac** [bireme/clinical-algorithms#55]
No PDF não está mostrando o nome das linhas que dividem os blocos de informações (aparecem na tela à esquerda), mas não constam no PDF gerado.

No PDF seria importante também constar informações sobre o respectivo algoritmo, tais como: título, autor, data de atualização e Logos Paho / Bireme.

Anexo: Print da tela e PDF correspondente - Parto Classic.
[Parto Classic.pdf](https://github.com/bireme/clinical-algorithms/files/14823960/Parto.Classic.pdf)

![Print - Parto Classic](https://github.com/bireme/clinical-algorithms/assets/107490628/d1c57b26-6a4b-4349-af2e-d6a914b526ca)

**Comment by RobertoPinaRizzo** [comment]
Recebemos estas demandas via e-mail da Sandra datado de 01/04. Foram colocados no Product Backlog.
