### ISSUE TITLE
fluxo: colocar um campo para DDI do pais

### ISSUE THREAD

**Issue by Lizbiruel** [bireme/clinical-algorithms#6]
![fluxograma_colocar cod de pais](https://github.com/bireme/clinical-algorithms/assets/25793512/62c0434b-1806-4ba1-8dcc-c6442e8125fe)
Como será um serviço regional, é necessário esse dado de identificação de pais

**Comment by RobertoPinaRizzo** [comment]
Adicionado no Product Backlog para implementação.

**Comment by Lizbiruel** [comment]
resolvido
