### ISSUE TITLE
Fluxo: dados de autoria não esta disponível

### ISSUE THREAD

**Issue by Lizbiruel** [bireme/clinical-algorithms#7]
![dados de autoria do fluxo_campo não esta disponível](https://github.com/bireme/clinical-algorithms/assets/25793512/30027c57-2a73-48a9-b3ab-923121c0180e)
Não esta aberto para ser preenchido

**Comment by RobertoPinaRizzo** [comment]
O campo estará aberto assim que for concluído o cadastro de usuários.

**Comment by Lizbiruel** [comment]
resolvido
