### ISSUE TITLE
Fluxo: demora para carregar o registro do fluxo

### ISSUE THREAD

**Issue by Lizbiruel** [bireme/clinical-algorithms#8]
![demora para carregar o registro do fluxo](https://github.com/bireme/clinical-algorithms/assets/25793512/1f3ea5d7-f4d0-46cc-bee8-f9b0c8f02007)
Parei aqui nos testes, NÃO CARREGA

**Comment by viniciusandrade** [comment]
@gabriel-silveira

Verifiquei no log do container que após alguma ação/evento aparentemente a API se torna indisponível e por isso o frontend para de carregar os dados dos fluxogramas conforme verificado pela @Lizbiruel ... segue log do container para análise:

[_clinical-algorithms-api_logs.txt](https://github.com/bireme/clinical-algorithms/files/13459869/_clinical-algorithms-api_logs.txt)

**Comment by viniciusandrade** [comment]
@Lizbiruel foi realizado um ajuste  no ambiente solicitado pelo desenvolvedor, por favor, quando possível tentar prosseguir com o teste. Obrigado.

**Comment by viniciusandrade** [comment]
Novos ajustes realizados para este comportamento: https://github.com/bireme/clinical-algorithms/pull/16

**Comment by Lizbiruel** [comment]
resolvido
