### ISSUE TITLE
Não consigo colocar o dado de autoria

### ISSUE THREAD

**Issue by Lizbiruel** [bireme/clinical-algorithms#9]
![1_não consigo editar o Titulo do fluxograma](https://github.com/bireme/clinical-algorithms/assets/25793512/ae009a5f-7609-4f57-b154-df9ab47d3c15)
Não consigo colocar o dado de autoria

**Comment by Lizbiruel** [comment]
![não é possível registrar autoria](https://github.com/bireme/clinical-algorithms/assets/25793512/78ab958a-4884-46bd-b568-efdec172ee13)
ignora a imagem anterior, essa é a imagem que vale

**Comment by RobertoPinaRizzo** [comment]
O campo de autoria está bloqueado porque depende da criação do cadastro de usuários. Assim que o cadastro for criado, este campo aqui será liberado para coleta.

**Comment by Lizbiruel** [comment]
resolvido
